
defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('OFN_DB_USERNAME', 'ofn_user') %>
  password: <%= ENV.fetch('OFN_DB_PASSWORD', 'DBPassword1234labelleorange') %>
  host: <%= ENV.fetch('OFN_DB_HOST', 'localhost') %>
  pool: <%= ENV.fetch('OFN_DB_POOL', 5) %>
  database: <%= ENV.fetch('OFN_DB_NAME', 'openfoodnetwork') %>

development:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
